# Application bindings
bindd = SUPER, RETURN, Terminal, exec, uwsm-app -- xdg-terminal-exec --dir="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER SHIFT, F, File manager, exec, uwsm-app -- nautilus --new-window
bindd = SUPER SHIFT, B, Browser, exec, omarchy-launch-browser
bindd = SUPER SHIFT ALT, B, Browser (private), exec, omarchy-launch-browser --private
bindd = SUPER SHIFT, M, Music, exec, omarchy-launch-or-focus spotify
bindd = SUPER SHIFT, N, Editor, exec, omarchy-launch-editor
bindd = SUPER SHIFT, D, Docker, exec, omarchy-launch-tui lazydocker
bindd = SUPER SHIFT, O, Obsidian, exec, omarchy-launch-or-focus ^obsidian$ "uwsm-app -- obsidian -disable-gpu --enable-wayland-ime"
bindd = SUPER SHIFT, SLASH, Passwords, exec, uwsm-app -- 1password

# If your web app url contains #, type it as ## to prevent hyprland treating it as a comment
bindd = SUPER SHIFT, A, ChatGPT, exec, omarchy-launch-webapp "https://chatgpt.com"

unbind = SUPER, C
unbind = SUPER, V
unbind = SUPER CTRL, V
bindd = CTRL SHIFT, V, Clipboard manager, exec, omarchy-launch-walker -m clipboard
bind = , Scroll_Lock, exec, omarchy-lock-screen

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
unbind = SUPER, W
bindd = SUPER, Q, Close window, killactive
bind = SUPER, R, exec, hyprctl reload

unbind = SUPER, code:10
unbind = SUPER, code:11
unbind = SUPER, code:12
unbind = SUPER, code:13
unbind = SUPER, code:14
unbind = SUPER, code:15
unbind = SUPER, code:16
unbind = SUPER, code:17·
unbind = SUPER, code:18
unbind = SUPER, code:19

bindd = SUPER, code:10, Switch to workspace 1, focusworkspaceoncurrentmonitor, 1
bindd = SUPER, code:11, Switch to workspace 2, focusworkspaceoncurrentmonitor, 2
bindd = SUPER, code:12, Switch to workspace 3, focusworkspaceoncurrentmonitor, 3
bindd = SUPER, code:13, Switch to workspace 4, focusworkspaceoncurrentmonitor, 4
bindd = SUPER, code:14, Switch to workspace 5, focusworkspaceoncurrentmonitor, 5
bindd = SUPER, code:15, Switch to workspace 6, focusworkspaceoncurrentmonitor, 6
bindd = SUPER, code:16, Switch to workspace 7, focusworkspaceoncurrentmonitor, 7
bindd = SUPER, code:17, Switch to workspace 8, focusworkspaceoncurrentmonitor, 8
bindd = SUPER, code:18, Switch to workspace 9, focusworkspaceoncurrentmonitor, 9
bindd = SUPER, code:19, Switch to workspace 10, focusworkspaceoncurrentmonitor, 10